// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi3o8GCRrQyQFUNSpgVVO1g3w5AENOzyo',
    appId: '1:205261715693:web:4f23e7706bcd267e56f4e4',
    messagingSenderId: '205261715693',
    projectId: 'medical-hackathon-8bbe9',
    authDomain: 'medical-hackathon-8bbe9.firebaseapp.com',
    storageBucket: 'medical-hackathon-8bbe9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TKIs5MLxSanfOkvRqtK5xnyAIAgajFg',
    appId: '1:205261715693:android:995e02b6eafa936c56f4e4',
    messagingSenderId: '205261715693',
    projectId: 'medical-hackathon-8bbe9',
    storageBucket: 'medical-hackathon-8bbe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwkx8ZzMgbfWlTsaq5dTSaHL0OyyJSO6M',
    appId: '1:205261715693:ios:b9cc402a4de14eee56f4e4',
    messagingSenderId: '205261715693',
    projectId: 'medical-hackathon-8bbe9',
    storageBucket: 'medical-hackathon-8bbe9.appspot.com',
    iosBundleId: 'com.example.nurseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwkx8ZzMgbfWlTsaq5dTSaHL0OyyJSO6M',
    appId: '1:205261715693:ios:f0a940900dc31f6a56f4e4',
    messagingSenderId: '205261715693',
    projectId: 'medical-hackathon-8bbe9',
    storageBucket: 'medical-hackathon-8bbe9.appspot.com',
    iosBundleId: 'com.example.nurseApp.RunnerTests',
  );
}
